USER1_NAME = "standard_user"
USER2_NAME = "problem_user"
USER3_NAME = "performance_glitch_user"
USER4_NAME = "error_user"
USER5_NAME = "visual_user"
USER_WRONG_NAME = "wrong_name"
USER_PASSWORD = "secret_sauce"
USER_WRONG_PASSWORD = "wrong_password"
LOGIN_ERROR_MESSAGE = "Epic sadface: Username and password do not match any user in this service"
USERNAME_REQUIRED_MESSAGE = "Epic sadface: Username is required"
PASSWORD_REQUIRED_MESSAGE = "Epic sadface: Password is required"
SQL_INJECTION_LOGIN = "' OR '1'='1"
XSS_LOGIN = "<script>alert(1)</script>"
CHECKOUT_FIRST_NAME = "Ivan"
CHECKOUT_LAST_NAME = "Ivanov"
CHECKOUT_ZIP = "12345"
CHECKOUT_COMPLETE_MESSAGE = "Checkout: Complete!"
